### ISSUE TITLE
Error: "Stormpath.AspNetCore 0.4.0 does not support .NetCoreApp"

### ISSUE THREAD

**Issue by DmsChrisPena** [stormpath/stormpath-aspnetcore#11]
So I installed Stormpath.AspNetCore through nuget and it doesn't install the package and gives this error. 

[Error Image](http://i.imgur.com/CyRG6kK.png)

I'm running the latest version of Core and it's a brand new project. Not sure if anyone is running into the this problem as well.

**Comment by nbarbettini** [comment]
Hey @DmsChrisPena, sorry about the error.

Would you mind posting your `project.json`, or at least the frameworks and dependencies sections?

**Comment by DmsChrisPena** [comment]
Here you go!

https://gist.github.com/DmsChrisPena/28d74305866251460880b7344dcf5a94

**Comment by nbarbettini** [comment]
I think Visual Studio is reporting the error incorrectly. I believe it's actually YamlDotNet (a dependency) that is causing problems.

Can you try adding `dotnet` to the `frameworks: imports` section? That should clear it up.

This won't be an issue once there's a true .NET Core version of YamlDotNet.

**Comment by DmsChrisPena** [comment]
I added dotnet to the framework imports:
`  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet",
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },`

but I'm still getting the same error.

Here is the error output.
https://gist.github.com/DmsChrisPena/54225b97f303524f9ab5dc203278c111

**Comment by nbarbettini** [comment]
Ah, I missed this before: all of your packages (in `project.json`) are RC2 versions. If you've already updated the .NET Core tooling on your machine, you'll also have to update the package references to point to RTM packages.

For reference, `dotnet --version` on my machine reports `1.0.0-preview2-003121`

Here's what an RTM `project.json` looks like (from the Stormpath ASP.NET Core example project): https://github.com/stormpath/stormpath-aspnetcore-example/blob/master/src/StormpathExample/project.json
(Notice the lack of `rc2` tags on the package versions, especially on `.NETCoreApp`)

**Comment by DmsChrisPena** [comment]
Gotcha, that makes perfect sense. I haven't updated for a couple months now so I guess that's a problem haha. It's frustrating at how unspecific of an error VS gave.

Anyways, thanks so much for the quick help and I look forward to trying out Stormpath!

**Comment by nbarbettini** [comment]
No problem! Happy to help. Let me know if you run into any other snags.
