### ISSUE TITLE
Hook to add claims to a JWT

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-aspnetcore#12]
Currently, a basic transformation is applied to JWTs that copies a few claims into the resulting ClaimsIdentity on each incoming request:
- Email
- First/last name
- Stormpath account href

In a future release, it should be possible to customize this and add anything to the ClaimsIdentity.

**Comment by jonathanamarsh** [comment]
Hi, this enhancement sounds pretty cool. Can I confirm that this will allow us to access the custom claims we may wish to add to a JWT, for example, alongside the ones currently provided out of the box (name, email, surname etc.)?

So, for instance, following the example here: https://support.stormpath.com/hc/en-us/articles/223281547-How-do-I-add-custom-claims-to-JWT-s-, if when generating a JWT, I add an extra claim such as "UserId", this claim would then be made available in User.Claims in the Controller.

**Comment by nbarbettini** [comment]
Yes, that sounds right.

This hook would allow you to customize any aspect of the JWT -> ClaimsIdentity transformation. Currently, a very basic transformation is applied (which would remain the default), but you could extend it however you wanted.

**Comment by omgitstom** [comment]
Hi @jonathanamarsh,

I manage Product @ Stormpath.  This is something I would like to add to the platform so you wont have to write any code to get something in the signed JWT.  Where do you get the UserId from?  Is this something that you store in custom data? Or something you need to look up at runtime?

Thanks for clarity here,
Tom

**Comment by jonathanamarsh** [comment]
Hi @omgitstom 

Currently we store user ids in our own database only, not in Stormpath custom data. When the user logs in, we authenticate the credentials with Stormpath, and if successful make a call to our database to grab the user id and then add this as a claim to the JWT.

As the vast majority of our API endpoints require the id of the current user,  the ideal situation for us is that this information is included in the JWT itself, as this saves us from having to make a dedicated call (either to our own database or to Stormpath) to get this value for each request.

As such the ability to add claims to a JWT and have these picked up and populated by the middleware out of the box, or alternatively, some option to serialise custom data as a set of claims would be very useful.

**Comment by nwolke** [comment]
I have just been looking for an answer for that FAQ page (even left a couple of comments there) about adding custom claims. I even created a new Login endpoint in a controller and ran the code in the FAQ, but it didn't actually change any claims at all. It always returned a base 6 claims, the last being the FullName of the account. I tried .SetClaims("foo", "myvalue!") but it isn't in the claims list of the HttpContext.User.Claims collection.
I'm pretty much in the same boat as @jonathanamarsh here. There are a couple of items that would definitely streamline my server API calls if I could just insert them into the claims collection.
Thanks!

**Comment by nbarbettini** [comment]
Hey @nwolke - it sounds like what you and @jonathanamarsh need is a hook that fires when the JWT is initially created, so you can add some extra claims. This issue was initially intended as something else: customizing the transformation that runs on each request to convert the JWT to a ClaimsIdentity.

Since the former use case seems to be a better fit, I'll investigate the feasibility of this type of hook. Thanks for the feedback!

**Comment by jonathanamarsh** [comment]
Hi @nwolke. I believe the middleware only extracts the “standard” Stormpath claims so to speak, so irrespective of additional claims you add on token creation, out of the box the middleware will only populate the Stormpath related claims (name, email etc.) for the request.

I don’t know if this will help you at all, but the approach we are using in the meantime is to use a Claims Transformer class (implementing *Microsoft.AspNetCore.Authentication.IClaimsTransformer*). This runs after the Stormpath middleware (so authentication etc. is already handled) and manually extracts the JWT from the request header, decodes it and gets the relevant claim which we then add to the request ClaimsPrincipal, making this additional claim available in our controllers.

@nbarbettini  Yes ideally, some means of adding claims to the token on creation, which are then populated automatically by the middleware would be very useful!

**Comment by nwolke** [comment]
@jonathanamarsh ya, i realized after reading the comments above that it was stated it always does the default claims. thanks for the extra clarification though.
I'm following up your advice with how I implemented it in case anybody else needs this workaround.
So, i implemented the IClaimsTransformer interface and the TransformAsync method in it. I grabbed my EF dbcontext object injected into the application by using `context.Context.RequestServices.GetRequiredServices<MyDbContext>()`. I then found the User by using the `context.Principal.Identity.Name` property (which is the email address in my case) and then dumped the claim into the principal.
Unfortunately, it seems this database call will happen on every call to the server but it'll work for my needs without having to resort to placing these searches in every controller action or elsewhere.
so, thanks for the advice!

**Comment by sicollins** [comment]
Any idea when this feature will be available?

**Comment by nbarbettini** [comment]
@sicollins et al, here is the current status of this request: we are planning to add support for mapping or adding custom claims to the core Stormpath API. This will provide the support the ASP.NET middleware (and others) need to do this for your applications. If it's a feature you want track, vote or subscribe to [this](https://ideas.stormpath.com/ideas/IAM-I-109) item on our Ideas board.

@omgitstom may want to chime in with any additional info.

**Comment by nelsonlainez** [comment]
We stopped waiting for StormPath to implement this, and coded our own stuff in order to integrate StormPath with ASP.NET Core, with custom claims in tokens and refresh tokes. But it was incredible painful...

**Comment by nbarbettini** [comment]
An update after the [Stormpath/Okta acquisition](https://stormpath.com/blog/stormpaths-new-path) - this feature won't be implemented in this library. But on the bright side, Okta has a robust set of features around mapping claims to the access and ID tokens.
