### ISSUE TITLE
/me path expand not working

### ISSUE THREAD

**Issue by nepodmitljivi** [stormpath/stormpath-aspnetcore#13]
Hi, can anybody confirm this is working
https://docs.stormpath.com/dotnet/aspnetcore/latest/me_api.html#me-expansion

Here is my yaml file
`---
  application:
    name: "My Storm"    
  web:
    me:
      enabled: true
      uri: "/userDetails"
      expand:
        customData: true

`
but I only get default stuff. Uri change is working but I cannot get custom data.
When I try using REST API I get customData (and everything else).
I have entered some custom data for the user but I don't know how to get it in ASP.NET Core.
Here is the response

> {
  "account": {
    "href": "https://api.stormpath.com/v1/accounts/blahblah",
    "username": "zlorf1@blahblah.com",
    "modifiedAt": "2016-07-22T16:38:33.609+00:00",
    "status": "ENABLED",
    "createdAt": "2016-07-22T13:01:37.313+00:00",
    "email": "zlorf1@blahblah.com",
    "middleName": null,
    "surname": "Flannelfoot",
    "givenName": "Zlorf",
    "fullName": "Zlorf Flannelfoot"
  }
}

Shouldn't there be a custom data as well? Like I said, It exists when I get user details with that href link.

I'm using Windows 10 + VS 2015 community edition and I downloaded stormpath example from
https://github.com/stormpath/stormpath-aspnetcore-example/tree/master/src/StormpathExample

**Comment by nbarbettini** [comment]
Hey @nepodmitljivi - your configuration is correct. There's currently some code missing for this feature, see this issue: https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/12

I'll be working on getting this fixed this week and I'll post here when it's ready to test. Sorry about the issue!

**Comment by nepodmitljivi** [comment]
Thx for the reply. Sorry I missed it in the OWIN section. :)

**Comment by nbarbettini** [comment]
Not a problem. It's a little hard to find! Sorry that the documentation doesn't line up with the expected behavior, that's my fault!

**Comment by nepodmitljivi** [comment]
Any progress with this?

**Comment by nbarbettini** [comment]
Yeah, it's almost done :) sorry for the delay. I'll update here when I have it merged in.

**Comment by nbarbettini** [comment]
Closed via https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/12

Sorry it took so long @nepodmitljivi!

**Comment by nepodmitljivi** [comment]
No problem, thanks. I'll test it and let you know if there are any issues.
