### ISSUE TITLE
Got 400 bad request on register account

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-aspnetcore#21]
Hi. I am sending post on http://localhost:5000/register and getting 400 bad request with message Cannot sanitize type 'IAccount'. But account is created on stormpath admin and all is good. So it looks strange at least. How can I get 201 or 200 instead?

**Comment by nbarbettini** [comment]
Do you have the latest version of the package? I fixed a bug like this in https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/27.

If this is happening with `Stormpath.AspNetCore` 0.6.0, then it's a new regression.

**Comment by consigliory** [comment]
I use latest available 0.6.0. Any ideas when it could be fixed?

**Comment by consigliory** [comment]
no sorry. even 0.6.0 was in packages there still was 0.5.0 now it works. Thanks!

**Comment by consigliory** [comment]
Thanks for this project!

**Comment by nbarbettini** [comment]
No problem! Glad it's working now. :)
