### ISSUE TITLE
AuthorizationHandlers called even though there's no authenticated user.

### ISSUE THREAD

**Issue by DiveboatSlave** [stormpath/stormpath-aspnetcore#22]
If I have a controller method protected by a policy [Authorize(Policy="PolicyName")], and I call this from an unauthenticated session, the StormpathAuthenticationHandler.HandleAuthenticateAsync will return a Task.FromResult(AuthenticateResult.Fail("Request is not properly authenticated.")) result. 

I would expect this to result in the StormpathAuthenticationHandler.HandleUnauthorizedAsync being called, but instead each of AuthorizationHandlers gets called for the Policy Requirements, and these then fail because the ScopedLazyUserAccessor returns a null IAccount (although there's a bug where the  ScopedLazyUserAccessor can return a previous logged in user).

Why are the Requirement handlers being called after the call to StormpathAuthenticationHandler.HandleAuthenticateAsync has failed? Is this expected behaviour?

**Comment by nbarbettini** [comment]
Thanks! I tested this myself but clearly missed something. I will look into it (and the other issue) ASAP.

By the way, feel free to jump into the [Talk Stormpath Slack](https://talkstormpath.shipit.xyz/) if you haven't already. You can DM me there if you have any other thoughts.

**Comment by DiveboatSlave** [comment]
Ok I get on Slack today Nate.

**Comment by nbarbettini** [comment]
Hey @DiveboatSlave - circling back around on this. I know the ScopedLazyUserAccessor bug was fixed, but are you still seeing this behavior in the newest release? Thanks for your patience. 😄
