### ISSUE TITLE
malformed Set-Cookie headers on logout

### ISSUE THREAD

**Issue by antoinebrault** [stormpath/stormpath-aspnetcore#23]
Hi,

I'm not sure if this is a ASP.NET Core issue or Stormpath, but on logout i'm getting malformed Set-Cookie headers.

Set-Cookie:access_token=path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT; HttpOnly
Set-Cookie:refresh_token=path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT; HttpOnly

It should have a semicolon+space after access_token=

I'm using stormpath-angular in a SPA and default configuration in ASP.NET (except for URIs).

I had to use the following code to output valid Set-Cookie: 

```
app.Use((context, next) =>
{
	if (context.Request.Path.Equals("/API/logout"))
	{
		context.Response.Cookies.Delete("access_token",
			new Microsoft.AspNetCore.Http.CookieOptions()
			{
				HttpOnly = true,
				Path = "/"
			});
		context.Response.Cookies.Delete("refresh_token",
			new Microsoft.AspNetCore.Http.CookieOptions()
			{
				HttpOnly = true,
				Path = "/"
			});
	}

	return next();
});

app.UseStormpath();
```

**Comment by nbarbettini** [comment]
Thanks for reporting @antoinebrault. I'll post updates here.

**Comment by nbarbettini** [comment]
Fixed and slated for [2.1.0](https://github.com/stormpath/stormpath-dotnet-owin-middleware/milestone/7).

**Comment by nbarbettini** [comment]
FYI, there is a beta package on the prerelease channel available, if you'd like to test: https://www.myget.org/F/stormpath-aspnetcore/api/v3/index.json

**Comment by nbarbettini** [comment]
Closed via https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/47.
