### ISSUE TITLE
[Authorize(Policy = "AdminGroup")] does not work 

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-aspnetcore#28]
Hi
unfortunately i can't attach any exception because there is no exceptions but I will try to describe issue. Looks like authorize policy uses some kind of cache and it fails and not related to state of authenticated user. So once user logged in all is fine and attribute works as expected but after some period of time user is still logged in and access token refreshed but user no longer passes authorize policy attribute. So either need to logout and login again or restart app.

**Comment by nbarbettini** [comment]
I fixed some issue related to this in version 0.7.0. Can you try the latest
release and see if that works?

**Comment by consigliory** [comment]
sure. Will check it. thanks

**Comment by consigliory** [comment]
unfortunately issue still exists

**Comment by consigliory** [comment]
for now it is not critical, but this is important part of app.

**Comment by nbarbettini** [comment]
Can you share the code that you are using to build the policy?

**Comment by consigliory** [comment]
Sorry just found it was cached old version. Seems all is great.

**Comment by consigliory** [comment]
My fault. Thanks

**Comment by nbarbettini** [comment]
No problem! Glad it's working.

For the record, the Groups lookup is never cached because the Stormpath SDK doesn't support collection caching. A CustomData lookup may be cached, though (if you are building a policy with `StormpathCustomDataRequirement`).

**Comment by consigliory** [comment]
services.AddAuthorization(opt =>
            {
                opt.AddPolicy("SuperAdminGroup", policy => policy.AddRequirements(new StormpathGroupsRequirement("SuperAdmin")));
            });

just in case I did it wrong

**Comment by nbarbettini** [comment]
Looks fine! 👍

**Comment by consigliory** [comment]
Unfortunat

**Comment by consigliory** [comment]
Looks like issue still exists. It is better but still not as it suppose to be. After some period of time user still logged in but cannot access resources with policy. Logout and in again solves problem but  is is not the way it should be

**Comment by nbarbettini** [comment]
I'll take a look. Do you have a set of reproduction steps?

**Comment by consigliory** [comment]
not really. but looks like it is related to refresh token time. I changed it to longer period and it is fails less frequent.

**Comment by nbarbettini** [comment]
Alright, that gives me something to go on, thanks.

**Comment by consigliory** [comment]
I meanwhile trying to solve it using claims and should be trivial. here the link from one your posts https://support.stormpath.com/hc/en-us/articles/223281547-How-do-I-add-custom-claims-to-JWT-s- . But custom claim not in claims once. So it is encoded properly and jwt does have custom claim. But when I read all existing claims it is not in the list var claims = User.Claims.Select(claim => new { claim.Type, claim.Value }).ToArray(); Do I need to do anything extra?!

**Comment by nbarbettini** [comment]
The Stormpath middleware applies a basic transformation to the JWT to copy it over to the ClaimsPrincipal. It ignores any extra claims that may exist. I'm open to changing this in the future.

**Comment by nbarbettini** [comment]
@consigliory I haven't been able to reproduce this. I've tried investigating what happens when the access token expires and is refreshed via the refresh token, but the authorization policy still works correctly.

Can you give me some more information about your application?
* I'm assuming you're using cookies to transport the access and refresh tokens?
* Is this an MVC app, or a Web API + JavaScript SPA app?
