### ISSUE TITLE
User.Claims contains only default values. No all claims included

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-aspnetcore#29]
Hi. Why not claims from token included in User.Claims? it is bug or is they way you planned it?! What do I need to do to be able to have  it in transformed to User.Claims

**Comment by nbarbettini** [comment]
There are a few claims that are automatically populated when a user is logged in:

- ClaimTypes.NameIdentifier (Stormpath Account href)
- ClaimTypes.Email
- ClaimTypes.Name (Stormpath username, usually the same as email)
- ClaimTypes.GivenName
- ClaimTypes.Surname
- "FullName" (The computed fullName property in Stormpath)

(From https://docs.stormpath.com/dotnet/aspnetcore/latest/request_objects.html#claimsidentity)

What other claims do you want in User.Claims?

**Comment by consigliory** [comment]
All which is included in payload. So if jwt has color:red, age:45 - this should be also included. So if I added custom things to jwt it should be possible to read them back too.

**Comment by consigliory** [comment]
Hi. Have not heard anything. So what could be done to have all claims included?

**Comment by nbarbettini** [comment]
Right now, it is not possible. I am investigating adding a customizable hook here: https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/30

**Comment by nbarbettini** [comment]
Quick update for you @consigliory - the customizable transformation didn't make it into the latest release, because it would require some significant refactoring under the hood. It is still planned but probably won't be available until later in Q4. Sorry for any inconvenience!

**Comment by consigliory** [comment]
any news?!

**Comment by nbarbettini** [comment]
Sorry that this got delayed @consigliory. Time pressure from other issues got in the way, sadly. It is still on the roadmap but I am not sure exactly when it will be (probably Q1). Apologies that I can't be more specific at the moment.

**Comment by nbarbettini** [comment]
Closing (see comment at https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/30)
