### ISSUE TITLE
account is null on action without [Authorize] attribute

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-aspnetcore#30]
I have actions which user can access with or without authentication. If user is authenticated and have certain role then this action can return more data. But it looks like if no [Authorize] attribute user is not initialized.

```
private readonly IAccount _stormpathAccount;
public DemoController(Lazy<IAccount> stormpathAccount)
        {
            _stormpathAccount = stormpathAccount.Value;
        }
```

**Comment by nbarbettini** [comment]
The presence of the `[Authorize]` attribute should not affect whether the user account is available on the request. Are you certain the user's cookies are attached to the request?

**Comment by consigliory** [comment]
there is no cookie. We use jwt (bearer token)

**Comment by nbarbettini** [comment]
Do you have console log output you can share?

**Comment by nbarbettini** [comment]
This test specifically checks this case: https://github.com/stormpath/stormpath-aspnet-tck/blob/master/src/Stormpath.AspNet.Tck/GetUserShould.cs#L39-L68

When run against this controller (no AuthorizeAttribute): https://github.com/stormpath/stormpath-aspnetcore/blob/master/test/Stormpath.AspNetCore.TckHarness/Controllers/UserController.cs

The test passes, so I haven't been able to reproduce your issue. Is it still occurring?
