### ISSUE TITLE
11k requests for very small dev app. 

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-aspnetcore#35]
Hi.
Real small app in dev stage produces 11k request a month. Looks like it is absolutely all request done is sent to stormpath and there is no caching of anykind for existing authenticated users. Do I do something wrong or should I expect several billion request account for production. Because for now it seems like only few users will match your top account.

**Comment by nbarbettini** [comment]
The Stormpath SDK includes a number of caching features which are on by default. See this section of the documentation: [Setting up caching](https://docs.stormpath.com/csharp/product-guide/latest/configuration.html#setting-up-caching). You can tweak the cache TTL and TTI for your application's needs.

Note that the default (in-memory) cache is suitable for an application hosted on a single server, but not an app hosted on multiple servers/a server farm. In that case, you'll need to plug in a distributed cache mechanism like Redis.

If you pull down an account (for example) by using `GetAccountAsync(string href)`, and then do the same thing again within the cache TTL/TTI, the request will not go to the network and will be fulfilled from the cache.

Collections are not cached, however. If you do `GetGroups().ToListAsync()`, that will always result in 1 or more network calls to pull down the whole collection from Stormpath. That may be where your unexpectedly high requests are coming from.
