### ISSUE TITLE
Middleware retrieves application from Stormpath on every request

### ISSUE THREAD

**Issue by Confusingboat** [stormpath/stormpath-aspnetcore#38]
We've been seeing ridiculously high Stormpath usage (resulting in exorbitant overage fees) and I've finally pinned it down to the middleware inexplicably grabbing the application from `api.stormpath.com` upon every single request.

I have removed all DI from my controllers, switched to manual retrieval, and put breakpoints on the only two root places I call the API, yet I still see Fiddler logging the middleware hitting `api.stormpath.com` on every request -- even those that don't need anything other than affirmation that the user is authenticated.

![image](https://cloud.githubusercontent.com/assets/519596/21466094/3125294c-c982-11e6-8428-509972bc4704.png)
I have marked the inital application load with red, the first request with blue, the second with green and the third with purple. It is my understanding that the green and purple sections should only have one request each -- the one hitting my own `/api/users/me` endpoint. I have even resorted to pulling the `UserId` out of the JWT cookie manually in order to lookup the internal user from SQL, but still I am seeing this.

Is this by design? This seems like something that should be cached.

**Comment by consigliory** [comment]
+1.

**Comment by nbarbettini** [comment]
This is a bug. I noticed this in some customer logs the other day as well.
It shouldn't be retrieving the Application resource repeatedly like this
(unless you have caching disabled of course).

I plan to release a minor SDK update next week to fix this and a few other
issues. Sorry about the frustration.

**Comment by nbarbettini** [comment]
FYI @Confusingboat @consigliory I'm tracking this here and will update when I push out a new package: https://github.com/stormpath/stormpath-sdk-dotnet/issues/237

**Comment by nbarbettini** [comment]
This is fixed as of [Stormpath.SDK 0.95.1](https://www.nuget.org/packages/Stormpath.SDK/0.95.1), but I will leave this issue open until the Stormpath.AspNetCore package has been updated to include the fixed SDK version.

**Comment by nbarbettini** [comment]
Thanks again for the bug reports y'all -- this is fixed in the SDK, and the new [Stormpath.AspNetCore 0.9.0](https://www.nuget.org/packages/Stormpath.AspNetCore/0.9.0) package consumes the updated version of the SDK.
