### ISSUE TITLE
Custom Views

### ISSUE THREAD

**Issue by Tibincrunch** [stormpath/stormpath-aspnetcore#40]
I have a couple weird things happening with custom Views. I'm trying to replace the default Login View with my own and have specified the path in my Startup.cs per the [documentation](https://docs.stormpath.com/dotnet/aspnetcore/latest/templates.html#custom-views).

```
Login = new WebLoginRouteConfiguration()
{
    Enabled = true,
    View = "~/Views/Stormpath/Login.cshtml",
    Uri = "/Account/Login"
},
```

My custom View appears if I'm already logged in, otherwise I get a 502.3 Bad Gateway error. In the custom View I have the [same code](https://github.com/stormpath/stormpath-dotnet-owin-middleware/blob/master/src/Stormpath.Owin.Views/Views/Stormpath/Login.cshtml) from this repository, however I changed the button text to Log In Test.

I've also noticed that specifying just the View name "Login" does not work at all... the default View is used instead.

Finally, it seems that the Uri route is case sensitive. Navigating to /account/login returns a 404 Not Found result while /Account/Login returns correctly. I'm not sure if this behavior is intended.

I'm still new to Stormpath so forgive me if these issues stem from my naivety. Thanks!

Edit: I originally posted this in the[ stormpath-dotnet-owin-middleware](https://github.com/stormpath/stormpath-dotnet-owin-middleware) repository but thought it might be more applicable here. I didn't realize that I would be unable to delete my other post.

**Comment by nbarbettini** [comment]
Hey @Tibincrunch, thanks for reaching out! Sorry for the weird error condition.

Can you try replacing your test view at `Views/Stormpath/Login.cshtml` with something really simple? The view in this repo is actually not valid Razor syntax (it's a long story - I need to document it better). Try starting with just `<html>Hello world!</html>` and see if that works. 

The other two issues sound like bugs or "unintended features". 😉  I'll be overhauling this functionality soon as part of a new release, so I'll be sure to note these.

No worries about posting in two places, you found the right one!

**Comment by nbarbettini** [comment]
Let me know if you need further help with building a custom view. I'm happy to help.

You can also jump into our [Slack channel](https://talkstormpath.shipit.xyz/) if you want. Cheers!

**Comment by Tibincrunch** [comment]
Thanks for the quick response @nbarbettini!

I replaced the contents of the custom View with `<html>Hello World!</html>` and still have the same results. While logged in the "Hello World!" text appears, otherwise I get a 502.3 Bad Gateway.

**Comment by nbarbettini** [comment]
I haven't been able to duplicate this yet. Here's what I tried:

Starting from https://github.com/stormpath/stormpath-aspnetcore-example, I changed my configuration:

```
            var stormpathConfiguration = new StormpathConfiguration()
            {
                Web = new WebConfiguration()
                {
                    Login = new WebLoginRouteConfiguration()
                    {
                        View = "~/Views/Stormpath/MyLogin.cshtml"
                    }
                }
            };
            services.AddStormpath(stormpathConfiguration);
```

Then I created `~/Views/Stormpath/MyLogin.cshtml`:

```
@model Stormpath.Owin.Abstractions.ViewModel.LoginFormViewModel
@using Stormpath.Owin.Abstractions

<form method="post" role="form">
    <input name="@StringConstants.StateTokenName" type="hidden" value="@Model.StateToken" />
    <input type="text" name="login" />
    <input type="password" name="password" />
    <div>
        <button type="submit">Log in</button>
    </div>
</form>
```

This works as expected. Can you send me a set of repro steps for your issue, or post your project here on Github? There must be something else going on.

**Comment by Tibincrunch** [comment]
You're right, something else must be interfering. I thought maybe targeting net452 in my project.json could be causing the issue.
```
"frameworks": {
    "net452": {}
  }
```
I tried to repro the issue in a fresh project with the same settings and could not. Thanks for taking a look! I'll reply here if I discover the problem.

**Comment by nbarbettini** [comment]
Sounds good! Thanks for following up. I'll close this for now, but feel free to reopen or create a new issue.
