### ISSUE TITLE
Unable to resolve 'Stormpath.SDK (>= 0.92.1)' for '.NETCoreApp,Version=v1.0'

### ISSUE THREAD

**Issue by eamodio** [stormpath/stormpath-aspnetcore#9]
It looks like Stormpath.SDK 0.92.1 wasn't pushed to nuget.

**Comment by nbarbettini** [comment]
Whoops, you're right. Somehow I missed it. It's up now: https://www.nuget.org/packages/Stormpath.SDK/0.92.1

@eamodio Can you try again and verify that everything works?

**Comment by eamodio** [comment]
@nbarbettini All looks good now -- thanks!
